### ISSUE TITLE
Look up recipes by the first letter

### ISSUE THREAD

**Issue by alexzjh21** [cesarsiguencia/dine-n-wine#1]
- When the user chooses to look up a recipe by the first letter and clicks on the button, the user will be shown a form to input the character of his/her choice. 
- Then, fetch data from themealdb API and get the list of meals that starts from a certain letter.
- Dynamically create <ul> to show the data.
- Make each <li> a button to call the specific recipe for the meal.
- Dynamically create <ol> to show data.

**Comment by Patrick-Fern** [comment]
This makes the web page too cluttered. Decided against
